import { useEffect,useState } from 'react'
import { db } from '../lib/firebase'
import { doc,getDoc,setDoc } from 'firebase/firestore'
const TIERS=['committed','developed','advanced','elite']
const parseLines=t=>t.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(label=>({key:label.toLowerCase().replace(/[^a-z0-9]+/g,'_'),label}))
export default function StandardsImport(){const[tier,setTier]=useState('committed');const[raw,setRaw]=useState('');const[msg,setMsg]=useState('');useEffect(()=>setMsg(''),[tier,raw])
const save=async e=>{e.preventDefault();const items=parseLines(raw);if(!items.length){setMsg('Add at least one line.');return}const ref=doc(db,'config','standards_by_tier');const snap=await getDoc(ref);const ex=snap.exists()?snap.data():{};ex[tier]=items;await setDoc(ref,ex,{merge:true});setMsg('Saved template ✓')}
const applyOne=async()=>{const uid=prompt('Enter member UID to apply this tier template to:');if(!uid)return;const ref=doc(db,'config','standards_by_tier');const s=await getDoc(ref);const tpl=s.exists()?(s.data()[tier]||[]):[];await setDoc(doc(db,'standards',uid),{items:tpl},{merge:true});setMsg('Applied to member ✓')}
return(<section className='space-y-4'><h2 className='text-2xl font-bold'>Standards Import (by Tier)</h2><p className='text-sm text-slate-600'>Paste one standard per line. Save per tier: committed, developed, advanced, elite.</p><div className='flex items-center gap-2'><span className='text-sm'>Tier</span><select className='border rounded px-2 py-1' value={tier} onChange={e=>setTier(e.target.value)}>{TIERS.map(t=><option key={t} value={t}>{t}</option>)}</select></div><textarea className='w-full border rounded p-3' rows='10' placeholder='e.g.\n1.5-mile ≤ 13:15\n100 pushups\n50 burpees' value={raw} onChange={e=>setRaw(e.target.value)}/><div className='flex items-center gap-2'><button onClick={save} className='px-3 py-2 rounded bg-slate-900 text-white'>Save Tier Template</button><button onClick={applyOne} className='px-3 py-2 rounded border'>Apply to a specific member…</button></div>{msg&&<p className='text-sm text-slate-600'>{msg}</p>}<p className='text-xs text-slate-500'>Templates: config/standards_by_tier • Member docs: standards/{'{uid}'}</p></section>)}
